Fix ActiveRecord version retrieval on Rails 3
Previously a889deb tried to create a Gem::Version out of a module rather than
the full version string, causing:

    ArgumentError: Malformed version number string ActiveRecord::VERSION

This fixes broken tests (https://travis-ci.org/matthuhiggins/foreigner/builds/56370433)
and db:migrate on Rails 3.2.